// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82Poh5FV9ofZPCKArL0iA4NfkmTzrn6E',
    appId: '1:983858227612:web:f20a4bebd9985ab8638059',
    messagingSenderId: '983858227612',
    projectId: 'flutter-arisan-app',
    authDomain: 'flutter-arisan-app.firebaseapp.com',
    storageBucket: 'flutter-arisan-app.firebasestorage.app',
    measurementId: 'G-ZX5YN7K988',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_aNZ1SWkyFDOzgThCedxjk71luEVe_EI',
    appId: '1:983858227612:android:8ea1d1a6eacee3df638059',
    messagingSenderId: '983858227612',
    projectId: 'flutter-arisan-app',
    storageBucket: 'flutter-arisan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQQosxP-n5uPcEE7_tcNuo7Fo8pzmwG0',
    appId: '1:983858227612:ios:f0ec07969e60b2e1638059',
    messagingSenderId: '983858227612',
    projectId: 'flutter-arisan-app',
    storageBucket: 'flutter-arisan-app.firebasestorage.app',
    iosClientId: '983858227612-k9s69pag5aj1voiskjtnbn6c7b7ttvhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.arisanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQQosxP-n5uPcEE7_tcNuo7Fo8pzmwG0',
    appId: '1:983858227612:ios:f0ec07969e60b2e1638059',
    messagingSenderId: '983858227612',
    projectId: 'flutter-arisan-app',
    storageBucket: 'flutter-arisan-app.firebasestorage.app',
    iosClientId: '983858227612-k9s69pag5aj1voiskjtnbn6c7b7ttvhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.arisanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC82Poh5FV9ofZPCKArL0iA4NfkmTzrn6E',
    appId: '1:983858227612:web:8e85fdf32f9b18ad638059',
    messagingSenderId: '983858227612',
    projectId: 'flutter-arisan-app',
    authDomain: 'flutter-arisan-app.firebaseapp.com',
    storageBucket: 'flutter-arisan-app.firebasestorage.app',
    measurementId: 'G-K2Z5RJGBJF',
  );
}
